print('******************************************')
print('              PROGRAM PYTHON')
print('          oleh : rafi nadhir abdurrahman')
print('             kelas : X PPLG 2')
print('******************************************')